name: Build Packages

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build]

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - x86_64
        sdk:
          - openwrt-24.10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Free disk space
        run: |
          sudo rm -rf /usr/lib/{jvm,llvm} /usr/local /usr/src/* /var/lib/gems /var/lib/mysql /var/lib/snapd /etc/skel /opt/{microsoft,az,hostedtoolcache,cni,mssql-tools,pipx} /usr/share/{az*,dotnet,swift,miniconda,gradle*,java,kotlinc,ri,sbt} /root/{.sbt,.local,.npm} /usr/libexec/gcc/x86_64-linux-gnu/14 /usr/lib/x86_64-linux-gnu/{*clang*,*LLVM*} /home/linuxbrew          

      - name: Hack daed packages
        run: |
          sed -i 's/$(BPF_DEPENDS)//g' daed/Makefile          

      - name: Build Packages
        uses: sbwml/openwrt-gh-action-sdk@helloworld
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: chinadns-ng daed dns2socks dns2tcp geoview hysteria ipt2socks lua-neturl luci-app-daed luci-app-homeproxy luci-app-nikki luci-app-openclash luci-app-passwall luci-app-passwall2 luci-app-ssr-plus microsocks naiveproxy pdnsd redsocks2 shadow-tls shadowsocks-libev shadowsocks-rust shadowsocksr-libev simple-obfs sing-box tcping trojan trojan-plus tuic-client v2ray-core v2ray-geodata v2ray-plugin xray-core xray-plugin
          KEY_BUILD: ${{ secrets.sign_key }}
          NO_REFRESH_CHECK: true
          IGNORE_ERRORS: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.sdk }}-${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Zip packages
        run: |
          zip -j ${{ matrix.arch }}-${{ matrix.sdk }}.zip bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
          echo -e "**文件说明** 🎈:\n" >> release.txt
          echo -e "1. 默认ssr与passwall的插件与依赖整合包\n" >> release.txt
          echo -e "2. 使用方法：将整合包上传到openwrt设备的tmp目录，输入命令 \`opkg install *.ipk\`\n" >> release.txt
          echo -e "3. 默认压缩包里包含ssr passwall bypass passwall2 插件\n" >> release.txt
          echo -e "4. 如果单独安装ssr与依赖，\`rm -rf {*passwall*,*bypass*,*homeproxy*}\`\n" >> release.txt
          
      - name: Upload packages
        uses: ncipollo/release-action@main
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          artifacts: "${{ matrix.arch }}-${{ matrix.sdk }}.zip,bin/packages/${{ matrix.arch }}/packages_ci/*.ipk"
          allowUpdates: true
          replacesArtifacts: true
          bodyFile: "release.txt"
          tag: ${{ github.run_number }}-${{ matrix.arch }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 10
          keep_minimum_runs: 2
    
      - name: Remove old Releases
        uses: dev-drprasad/delete-older-rel
